spring.application.name=ms-inventario
server.port=8085

# Conexión corregida con parámetro de auto-creación para db_inventario
spring.datasource.url=jdbc:mysql://localhost:3306/db_inventario?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

# Hibernate: Configuración estándar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# --- CONFIGURACIÓN DE SWAGGER (AGREGA ESTO) ---
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/api/inventario/v3/api-docs