spring.application.name=ms-clientes
# Puerto específico para Clientes (NO EL 8080)
server.port=8082

# Conexión a la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/db_clientes?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true