server:
  port: 9090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # --- CONFIGURACIÓN GLOBAL DE CORS (SOLUCIONA EL ERROR RED) ---
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        # 1. CLIENTES - Puerto 8082
        - id: ms-clientes
          uri: http://localhost:8082
          predicates:
            - Path=/api/clientes/**, /api/direcciones/**

        # 2. PRODUCTOS - Puerto 8081
        - id: ms-productos
          uri: http://localhost:8081
          predicates:
            - Path=/api/productos/**, /api/categorias/**, /api/ofertas/**

        # 3. INVENTARIO - Puerto 8085
        - id: ms-inventario
          uri: http://localhost:8085 
          predicates:
            - Path=/api/movimientos**, /api/bodegas/**, /api/inventario/**

        # 4. PROVEEDORES - Puerto 8083
        - id: ms-proveedores
          uri: http://localhost:8083
          predicates:
            - Path=/api/proveedores/**, /api/suministros/**, /api/contactos/**

        # 5. VENTAS - Puerto 8084
        - id: ms-ventas
          uri: http://localhost:8084
          predicates:
            - Path=/api/ventas/**, /api/metodos-pago/**

        # 6. RECLAMOS - Puerto 8087
        - id: ms-reclamos
          uri: http://localhost:8087
          predicates:
            - Path=/api/reclamos/**, /api/historial/**, /api/resoluciones/**, /v3/api-docs/**

# --- CONFIGURACIÓN DE SWAGGER EN EL GATEWAY ---
springdoc:
  swagger-ui:
    urls:
      - name: Servicio Reclamos
        url: /api/reclamos/v3/api-docs