spring.application.name=ms_reclamos
server.port=8087
spring.datasource.url=jdbc:mysql://localhost:3306/db_reclamos
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- CONFIGURACIÓN DE SWAGGER (LIMPIA Y SIN REPETIR) ---
springdoc.api-docs.path=/api/reclamos/v3/api-docs
springdoc.swagger-ui.enabled=false
springdoc.swagger-ui.operations-sorter=alpha

# --- CONFIGURACIÓN DE CORS GLOBAL ---
spring.mvc.cors.allowed-origins=*
spring.mvc.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.mvc.cors.allowed-headers=*
