spring.application.name=ms-calificacion

# Cambiado al puerto 8088 para que corresponda a la ruta de calificaciones en el Gateway
server.port=8088

# Agregado el parámetro (?createDatabaseIfNotExist=true) para que XAMPP cree la base de datos db_calificaciones sola
spring.datasource.url=jdbc:mysql://localhost:3306/db_calificaciones?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

# Configuración JPA e Hibernate estándar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# --- CONFIGURACIÓN DE SWAGGER (AGREGA ESTO) ---
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/api/calificaciones/v3/api-docs