spring.application.name=ms-productos
server.port=8081

# Agregado el parámetro (?createDatabaseIfNotExist=true) para que XAMPP cree la base de datos db_productos automáticamente
spring.datasource.url=jdbc:mysql://localhost:3306/db_productos?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- CONFIGURACIÓN DE SWAGGER ---
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/api/productos/v3/api-docs