spring.application.name=ms-soporte
server.port=8086

spring.datasource.url=jdbc:mysql://localhost:3306/db_soporte?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

spring.main.allow-bean-definition-overriding=true