server.port=8089
spring.application.name=ms-pedidos

# --- CONFIGURACIÓN DE BASE DE DATOS ---
spring.datasource.url=jdbc:mysql://localhost:3306/db_pedidos?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

# --- CONFIGURACIÓN DE JPA / HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# --- CONFIGURACIÓN DE SWAGGER / OPENAPI ---
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/api/pedidos/v3/api-docs

# --- CONFIGURACIÓN DE MONITOREO (ACTUATOR) ---
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
logging.level.org.springframework.cloud.openfeign=DEBUG