spring.application.name=ms-proveedores
# Puerto único para Proveedores
server.port=8083

# Conexión corregida con parámetro de auto-creación para db_proveedores
spring.datasource.url=jdbc:mysql://localhost:3306/db_proveedores?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

# Hibernate: Crea tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# --- CONFIGURACIÓN DE SWAGGER (AGREGA ESTO) ---
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/api/proveedores/v3/api-docs